import { Project, UserProfile, NotificationItem, ActivityLog } from '../types';

export const initialUserProfile: UserProfile = {
  id: 'usr_01h892x',
  email: 'alex.vance@auratech.ai',
  fullName: 'Alex Vance',
  companyName: 'Aura Tech Intelligence',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  role: 'Product Lead & Founder',
  createdAt: '2026-01-15T09:00:00.000Z',
  usageQuota: {
    projectsUsed: 4,
    projectsLimit: 15,
    mediaProcessed: 142,
    storageUsedGb: 2.8,
    storageLimitGb: 10.0,
  },
};

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif_1',
    title: 'Instagram Extraction Complete',
    message: 'Extracted 32 media assets from @koa_coffee_co successfully.',
    timestamp: '10 mins ago',
    read: false,
    type: 'success',
  },
  {
    id: 'notif_2',
    title: 'Brand Palette Detected',
    message: 'Primary blue #0B2545 and secondary gold #C59B27 auto-extracted.',
    timestamp: '1 hour ago',
    read: false,
    type: 'info',
  },
  {
    id: 'notif_3',
    title: 'Ready for Export Pipeline',
    message: 'Luxe Aesthetics Studio passed validation check (100% readiness score).',
    timestamp: '3 hours ago',
    read: true,
    type: 'success',
  },
  {
    id: 'notif_4',
    title: 'Instagram Auth Syncing',
    message: 'Graph API token refreshed for account verification.',
    timestamp: '1 day ago',
    read: true,
    type: 'warning',
  },
];

export const initialActivityLogs: ActivityLog[] = [
  {
    id: 'act_101',
    projectId: 'proj_koa_01',
    projectTitle: 'Koa & Coast Coffee Co.',
    action: 'Created new Instagram profile transformation pipeline',
    timestamp: 'Today at 09:14 AM',
    user: 'Alex Vance',
    status: 'completed',
  },
  {
    id: 'act_102',
    projectId: 'proj_luxe_02',
    projectTitle: 'Luxe Aesthetics Studio',
    action: 'Generated brand design tokens & color mapping',
    timestamp: 'Yesterday at 04:30 PM',
    user: 'Alex Vance',
    status: 'completed',
  },
  {
    id: 'act_103',
    projectId: 'proj_apex_03',
    projectTitle: 'Apex Performance Gym',
    action: 'Parsed bio, location & business hours from Instagram metadata',
    timestamp: '2 days ago',
    user: 'System Auto-Parser',
    status: 'completed',
  },
  {
    id: 'act_104',
    projectId: 'proj_verve_04',
    projectTitle: 'Verve Creative Agency',
    action: 'Exported website structure & Loveable AI prompts',
    timestamp: '3 days ago',
    user: 'Alex Vance',
    status: 'completed',
  },
];

export const initialProjects: Project[] = [
  {
    id: 'proj_koa_01',
    businessName: 'Koa & Coast Coffee Co.',
    instagramUrl: 'https://instagram.com/koa_coffee_co',
    industry: 'Hospitality & Dining',
    status: 'ready',
    createdAt: '2026-08-01T10:15:00.000Z',
    updatedAt: '2026-08-03T14:20:00.000Z',
    notes: 'Artisanal coastal espresso bar with organic single-origin roasts and fresh bakery goods.',
    mediaCount: 28,
    readinessScore: 95,
    businessInfo: {
      businessName: 'Koa & Coast Coffee Co.',
      instagramHandle: '@koa_coffee_co',
      instagramUrl: 'https://instagram.com/koa_coffee_co',
      industry: 'Hospitality & Dining',
      phone: '+1 (555) 234-8901',
      email: 'hello@koacoastcoffee.com',
      address: '742 Ocean Avenue, Malibu, CA 90265',
      operatingHours: 'Mon-Sun: 6:30 AM – 6:00 PM',
      bio: 'Coastal specialty coffee & seasonal pour-overs. Handcrafted in Malibu with sustainable beans. 🌿☕️',
      websiteUrl: 'https://koacoastcoffee.com',
      services: ['Specialty Espresso Bar', 'Cold Brew on Tap', 'Artisanal Bakery & Toast', 'Private Event Catering', 'Subscription Coffee Beans'],
      notes: 'High engagement on outdoor terrace photos and single-origin pour-over reels.',
    },
    branding: {
      primaryColor: '#052b66',
      secondaryColor: '#45cc42',
      accentColor: '#E2B857',
      backgroundColor: '#F8FAFC',
      textColor: '#0F172A',
      headingFont: 'Playfair Display',
      bodyFont: 'Plus Jakarta Sans',
      personality: {
        professionalism: 85,
        minimalism: 90,
        vibrancy: 70,
        luxury: 80,
      },
      logoUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=300&auto=format&fit=crop&q=80',
    },
    generatedCopy: {
      heroHeadline: 'Artisanal Coastal Coffee Handcrafted for Mindful Mornings',
      heroSubheadline: 'Single-origin pour-overs, specialty espresso, and fresh seasonal pastries roasted sustainably along the Malibu coastline.',
      aboutText: 'Founded in Malibu, Koa & Coast Coffee Co. brings together ethically sourced beans, precision roasting, and a warm oceanfront atmosphere. We believe coffee is more than a morning habit—it is a daily ritual of connection and clarity.',
      servicesIntro: 'Crafted with care, served with intention.',
      servicesList: [
        {
          title: 'Specialty Espresso Bar',
          description: 'Precision-brewed espresso drinks featuring house-made syrups and organic oat milk.',
        },
        {
          title: 'Micro-Lot Pour Overs',
          description: 'Rotating single-origin beans sourced directly from fair-trade micro-farmers.',
        },
        {
          title: 'Artisanal Coastal Bakery',
          description: 'Baked fresh daily using organic sourdough, seasonal fruits, and butter pastry dough.',
        },
        {
          title: 'Whole Bean Subscription',
          description: 'Freshly roasted beans delivered to your doorstep weekly or monthly with custom grind profiles.',
        },
      ],
      ctaHeadline: 'Visit Our Malibu Coastal Espresso Bar Today',
      ctaButtonText: 'View Today’s Menu',
      faqs: [
        {
          question: 'Where do you source your coffee beans?',
          answer: 'We directly trade with small-holder shade-grown coffee farms in Ethiopia, Colombia, and Costa Rica.',
        },
        {
          question: 'Do you offer vegan pastry options?',
          answer: 'Yes! Over 50% of our daily bakery selection includes gluten-free and plant-based treats.',
        },
        {
          question: 'Are pets allowed in the outdoor patio?',
          answer: 'Absolutely. Our Malibu patio is 100% dog-friendly with fresh water bowls provided.',
        },
      ],
      seoMeta: {
        title: 'Koa & Coast Coffee Co. | Specialty Espresso & Pour-Over Bar in Malibu',
        description: 'Discover Malibu’s premier coastal coffee shop. Organic single-origin pour-overs, artisanal espresso, and fresh sourdough bakery.',
        keywords: ['Malibu coffee shop', 'specialty espresso bar', 'organic pour over', 'coastal bakery', 'coffee bean subscription'],
      },
    },
    media: [
      {
        id: 'med_1',
        projectId: 'proj_koa_01',
        url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&auto=format&fit=crop&q=80',
        caption: 'Morning sunshine streaming over our signature flat white. Sourced from Ethiopian Yirgacheffe notes. ☀️☕️',
        category: 'Product',
        qualityScore: 98,
        isHeroCandidate: true,
        aspectRatio: '1:1',
        likesCount: 1240,
        commentsCount: 88,
        extractedDate: '2026-08-01',
      },
      {
        id: 'med_2',
        projectId: 'proj_koa_01',
        url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&auto=format&fit=crop&q=80',
        caption: 'Our cozy wood-panelled indoor seating area with ocean views.',
        category: 'Atmosphere',
        qualityScore: 92,
        isHeroCandidate: false,
        aspectRatio: '4:3',
        likesCount: 950,
        commentsCount: 42,
        extractedDate: '2026-08-01',
      },
      {
        id: 'med_3',
        projectId: 'proj_koa_01',
        url: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=800&auto=format&fit=crop&q=80',
        caption: 'Barista Sam pulling a double shot with precision crema.',
        category: 'Team',
        qualityScore: 96,
        isHeroCandidate: true,
        aspectRatio: '1:1',
        likesCount: 1100,
        commentsCount: 65,
        extractedDate: '2026-08-02',
      },
      {
        id: 'med_4',
        projectId: 'proj_koa_01',
        url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&auto=format&fit=crop&q=80',
        caption: 'Freshly baked cardamom buns hot out of the oven every morning at 7 AM.',
        category: 'Product',
        qualityScore: 90,
        isHeroCandidate: false,
        aspectRatio: '1:1',
        likesCount: 830,
        commentsCount: 31,
        extractedDate: '2026-08-02',
      },
    ],
    exports: {
      id: 'exp_koa_1',
      projectId: 'proj_koa_01',
      loveablePrompt: 'Build a modern, high-converting landing page for Koa & Coast Coffee Co., an artisanal coastal coffee shop in Malibu. Use primary blue #052b66 and accent green #45cc42 with warm cream backgrounds. Feature a hero section with headline "Artisanal Coastal Coffee Handcrafted for Mindful Mornings", interactive menu tab, photo gallery with lightbox, Google maps location widget, and subscription sign-up card.',
      jsonExport: JSON.stringify({
        businessName: 'Koa & Coast Coffee Co.',
        industry: 'Hospitality & Dining',
        branding: { primary: '#052b66', secondary: '#45cc42', fonts: 'Playfair Display + Plus Jakarta Sans' },
        sections: ['Hero', 'Story', 'Services/Menu', 'Gallery', 'Testimonials', 'Contact & Hours'],
      }, null, 2),
      markdownExport: `# Koa & Coast Coffee Co. – Website Specification Document\n\n## Overview\n- **Business Name:** Koa & Coast Coffee Co.\n- **Industry:** Hospitality & Dining\n- **Primary Color:** #052b66\n- **Accent Color:** #45cc42\n\n## Hero Section\n- **Headline:** Artisanal Coastal Coffee Handcrafted for Mindful Mornings\n- **Subheadline:** Single-origin pour-overs, specialty espresso, and fresh seasonal pastries roasted sustainably along the Malibu coastline.\n- **CTA:** View Today's Menu\n\n## Key Services\n1. Specialty Espresso Bar\n2. Micro-Lot Pour Overs\n3. Artisanal Coastal Bakery\n4. Whole Bean Subscription`,
      createdAt: '2026-08-03T15:00:00.000Z',
      downloadCount: 2,
    },
  },
  {
    id: 'proj_luxe_02',
    businessName: 'Luxe Aesthetics Studio',
    instagramUrl: 'https://instagram.com/luxe_aesthetics_la',
    industry: 'Beauty & Salon',
    status: 'in_progress',
    createdAt: '2026-08-02T11:00:00.000Z',
    updatedAt: '2026-08-03T18:45:00.000Z',
    notes: 'High-end medical spa specializing in bespoke facial treatments and holistic skin renewal.',
    mediaCount: 42,
    readinessScore: 78,
    businessInfo: {
      businessName: 'Luxe Aesthetics Studio',
      instagramHandle: '@luxe_aesthetics_la',
      instagramUrl: 'https://instagram.com/luxe_aesthetics_la',
      industry: 'Beauty & Salon',
      phone: '+1 (555) 987-6543',
      email: 'concierge@luxeaesthetics.com',
      address: '9400 Wilshire Blvd, Beverly Hills, CA 90212',
      operatingHours: 'Tue-Sat: 9:00 AM – 7:00 PM',
      bio: 'Bespoke clinical facials, laser rejuvenation & holistic medical aesthetics in Beverly Hills. ✨🌿',
      websiteUrl: 'https://luxeaesthetics.com',
      services: ['Custom Hydrafacials', 'Collagen Laser Therapy', 'Bespoke Peels', 'Lymphatic Drainage Massage', 'Skincare Consultations'],
      notes: 'Extracted high quality before/after transformations and clean marble studio interior photos.',
    },
    branding: {
      primaryColor: '#052b66',
      secondaryColor: '#45cc42',
      accentColor: '#D4AF37',
      backgroundColor: '#FAFAFA',
      textColor: '#18181B',
      headingFont: 'Cinzel',
      bodyFont: 'Inter',
      personality: {
        professionalism: 95,
        minimalism: 85,
        vibrancy: 40,
        luxury: 98,
      },
      logoUrl: 'https://images.unsplash.com/photo-1560750588-73207b1ef5b8?w=300&auto=format&fit=crop&q=80',
    },
    generatedCopy: {
      heroHeadline: 'Tailored Aesthetic Care for Radiant & Youthful Skin',
      heroSubheadline: 'Experience non-invasive clinical skincare and bespoke rejuvenation treatments curated by Beverly Hills dermatological specialists.',
      aboutText: 'Luxe Aesthetics Studio combines advanced clinical science with serene luxury wellness. Every treatment plan is custom-crafted to restore your natural glow and elevate skin vitality.',
      servicesIntro: 'Pinnacle skincare treatments engineered for immediate and lasting results.',
      servicesList: [
        {
          title: 'Bespoke HydraFacial MD',
          description: 'Deep cleansing, gentle exfoliation, and intense hydration infused with antioxidant serums.',
        },
        {
          title: 'Laser Skin Resurfacing',
          description: 'Precision collagen-stimulating laser treatment to diminish fine lines and even tone.',
        },
        {
          title: 'Sculpting Facial Massage',
          description: 'Japanese Lymphatic drainage technique combined with gua sha micro-current lifting.',
        },
      ],
      ctaHeadline: 'Book Your Confidential Skincare Consultation Today',
      ctaButtonText: 'Reserve Appointment',
      faqs: [
        {
          question: 'Do I need a consultation prior to my first treatment?',
          answer: 'Yes, all new clients undergo a comprehensive digital skin diagnosis with our master aesthetician.',
        },
      ],
      seoMeta: {
        title: 'Luxe Aesthetics Studio | Beverly Hills MedSpa & Bespoke Facials',
        description: 'Beverly Hills clinical medical spa offering bespoke facials, laser rejuvenation, and advanced skincare.',
        keywords: ['Beverly Hills medspa', 'custom facial', 'laser skin resurfacing', 'luxury aesthetics'],
      },
    },
    media: [
      {
        id: 'med_201',
        projectId: 'proj_luxe_02',
        url: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&auto=format&fit=crop&q=80',
        caption: 'Relaxing facial treatment room designed with serene Italian marble.',
        category: 'Atmosphere',
        qualityScore: 97,
        isHeroCandidate: true,
        aspectRatio: '1:1',
        likesCount: 2310,
        commentsCount: 112,
        extractedDate: '2026-08-02',
      },
      {
        id: 'med_202',
        projectId: 'proj_luxe_02',
        url: 'https://images.unsplash.com/photo-1512290900676-26c2a48f413d?w=800&auto=format&fit=crop&q=80',
        caption: 'Organic botanical glow serum applied during our platinum facial.',
        category: 'Product',
        qualityScore: 94,
        isHeroCandidate: true,
        aspectRatio: '1:1',
        likesCount: 1890,
        commentsCount: 78,
        extractedDate: '2026-08-02',
      },
    ],
  },
  {
    id: 'proj_apex_03',
    businessName: 'Apex Performance Gym',
    instagramUrl: 'https://instagram.com/apex_performance_gym',
    industry: 'Fitness & Wellness',
    status: 'draft',
    createdAt: '2026-08-03T08:30:00.000Z',
    updatedAt: '2026-08-03T08:30:00.000Z',
    notes: 'High-intensity athletic conditioning facility with elite coaching and biomechanics lab.',
    mediaCount: 18,
    readinessScore: 45,
    businessInfo: {
      businessName: 'Apex Performance Gym',
      instagramHandle: '@apex_performance_gym',
      instagramUrl: 'https://instagram.com/apex_performance_gym',
      industry: 'Fitness & Wellness',
      phone: '+1 (555) 432-1098',
      email: 'info@apexperformance.fit',
      address: '1200 Industrial Parkway, Austin, TX 78702',
      operatingHours: 'Mon-Fri: 5:00 AM – 9:00 PM, Sat: 7:00 AM – 4:00 PM',
      bio: 'Austin’s premier strength & conditioning laboratory. Elite group training, mobility & recovery. 💪⚡️',
      websiteUrl: 'https://apexperformance.fit',
      services: ['Strength & Conditioning', '1-on-1 Personal Coaching', 'Infrared Sauna & Cold Plunge', 'Biomechanics Screening'],
      notes: 'Need additional photos of recovery lounge and turf zone.',
    },
    branding: {
      primaryColor: '#052b66',
      secondaryColor: '#45cc42',
      accentColor: '#FF3B30',
      backgroundColor: '#0F172A',
      textColor: '#F8FAFC',
      headingFont: 'Montserrat',
      bodyFont: 'Plus Jakarta Sans',
      personality: {
        professionalism: 90,
        minimalism: 70,
        vibrancy: 95,
        luxury: 60,
      },
    },
    generatedCopy: {
      heroHeadline: 'Unlock Your Peak Athletic Potential in Austin',
      heroSubheadline: 'Data-driven strength training, recovery plunge suites, and expert performance coaching engineered for high performers.',
      aboutText: 'Apex Performance is built for individuals who demand progress. Our science-backed conditioning protocols and state-of-the-art facility empower you to move stronger, recover faster, and train smarter.',
      servicesIntro: 'Uncompromising fitness facilities and personalized coaching.',
      servicesList: [
        { title: 'Performance Group Conditioning', description: 'Dynamic strength and cardiovascular sessions designed for measurable power gains.' },
        { title: 'Cold Plunge & Sauna Recovery', description: 'Contrast therapy suites to reduce inflammation and optimize central nervous system recovery.' },
      ],
      ctaHeadline: 'Claim Your Complimentary 3-Day All-Access Pass',
      ctaButtonText: 'Claim Free Pass',
      faqs: [
        { question: 'What experience level is required for group sessions?', answer: 'We welcome all fitness levels; every movement is scaled by our head biomechanics coaches.' },
      ],
      seoMeta: {
        title: 'Apex Performance Gym | Austin Strength & Athletic Recovery Center',
        description: 'Austin TX high-performance gym with strength training, contrast therapy cold plunge, and personal coaching.',
        keywords: ['Austin gym', 'strength and conditioning', 'cold plunge Austin', 'athletic training'],
      },
    },
    media: [
      {
        id: 'med_301',
        projectId: 'proj_apex_03',
        url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
        caption: 'Heavy barbell squat workstation in action.',
        category: 'Portfolio',
        qualityScore: 91,
        isHeroCandidate: true,
        aspectRatio: '1:1',
        likesCount: 1420,
        commentsCount: 54,
        extractedDate: '2026-08-03',
      },
    ],
  },
  {
    id: 'proj_verve_04',
    businessName: 'Verve Creative Agency',
    instagramUrl: 'https://instagram.com/verve_studio_ny',
    industry: 'Creative Studio',
    status: 'exported',
    createdAt: '2026-07-28T14:10:00.000Z',
    updatedAt: '2026-08-01T11:00:00.000Z',
    notes: 'Boutique branding studio in Soho specializing in luxury fashion and digital identity.',
    mediaCount: 35,
    readinessScore: 100,
    businessInfo: {
      businessName: 'Verve Creative Agency',
      instagramHandle: '@verve_studio_ny',
      instagramUrl: 'https://instagram.com/verve_studio_ny',
      industry: 'Creative Studio',
      phone: '+1 (555) 765-4321',
      email: 'studio@verveagency.com',
      address: '480 Broadway, Soho, New York, NY 10013',
      operatingHours: 'Mon-Fri: 9:00 AM – 6:00 PM',
      bio: 'Brand design, 3D motion & editorial art direction for ambitious global lifestyle brands. 🎨🗽',
      websiteUrl: 'https://verveagency.com',
      services: ['Brand Identity & Visual Systems', 'Art Direction & Photoshoots', '3D Motion Design', 'E-commerce UI/UX'],
      notes: 'Complete export delivered to Framer/Loveable pipeline.',
    },
    branding: {
      primaryColor: '#052b66',
      secondaryColor: '#45cc42',
      accentColor: '#10B981',
      backgroundColor: '#F8FAFC',
      textColor: '#0F172A',
      headingFont: 'Space Grotesk',
      bodyFont: 'Plus Jakarta Sans',
      personality: {
        professionalism: 92,
        minimalism: 95,
        vibrancy: 88,
        luxury: 85,
      },
    },
    generatedCopy: {
      heroHeadline: 'Distilling Brand Essence into Unforgettable Digital Experiences',
      heroSubheadline: 'Soho-based branding and 3D motion design studio crafting high-impact visual identities for next-generation consumer brands.',
      aboutText: 'Verve Creative Agency partners with visionary founders to build magnetic visual ecosystems.',
      servicesIntro: 'Tailored branding and motion design services.',
      servicesList: [
        { title: 'Brand Identity Systems', description: 'Comprehensive design frameworks including custom typography, color palettes, and brand guidelines.' },
      ],
      ctaHeadline: 'Let’s Build Something Iconic Together',
      ctaButtonText: 'Schedule Studio Call',
      faqs: [],
      seoMeta: {
        title: 'Verve Creative Agency | Soho NYC Brand Design & Motion Studio',
        description: 'Boutique Soho NYC branding studio for luxury lifestyle brands and visual identities.',
        keywords: ['Soho branding agency', 'NYC design studio', '3D motion design', 'luxury brand identity'],
      },
    },
    media: [
      {
        id: 'med_401',
        projectId: 'proj_verve_04',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
        caption: 'Editorial print branding mockups layout on linen canvas.',
        category: 'Portfolio',
        qualityScore: 99,
        isHeroCandidate: true,
        aspectRatio: '16:9',
        likesCount: 3100,
        commentsCount: 140,
        extractedDate: '2026-07-28',
      },
    ],
    exports: {
      id: 'exp_verve_1',
      projectId: 'proj_verve_04',
      loveablePrompt: 'Create an editorial luxury studio website for Verve Creative Agency in Soho NYC. High contrast monochrome with electric green accents (#45cc42). Grid portfolio showcase, smooth cursor animations, client roster, and interactive project brief generator.',
      jsonExport: JSON.stringify({ businessName: 'Verve Creative Agency', industry: 'Creative Studio' }, null, 2),
      markdownExport: `# Verve Creative Agency Export Spec\n...`,
      createdAt: '2026-08-01T11:00:00.000Z',
      downloadCount: 5,
    },
  },
];
